import{a as d,S as f,i as n}from"./assets/vendor-CIu9XFSi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const g="52981451-85a14668d3ac889bbcbd31730";function y(i=""){return d("https://pixabay.com/api/",{params:{key:g,q:i,image_type:"photos",orientation:"horizontal",safesearch:!0}}).then(({data:t})=>t)}const l=document.querySelector(".gallery"),u=document.querySelector(".loader");let h=new f(".image-pixabay a",{captions:!0,captionsData:"alt",captionDelay:250,overlayOpacity:1});function b(i){l.innerHTML=i.map(({webformatURL:t,largeImageURL:o,tags:s,likes:e,views:r,comments:a,downloads:p})=>`<li class="image-pixabay">
            <a href=${o}><img src="${t}" alt="${s}" width='360' class="image-icon"/></a>
            <ul class="image-descriptions">
              <li class="image-text">Likes <br><span>${e}</span></li>
              <li class="image-text">Views <br><span>${r}</span></li>
              <li class="image-text">Comments <br><span>${a}</span></li>
              <li class="image-text">Downloads <br><span>${p}</span></li>
            </ul>
        </li>`).join(""),h.refresh()}function L(){l.innerHTML=""}function x(){u.classList.add("hidden")}function S(){u.classList.remove("hidden")}const m=document.querySelector(".form"),c=document.querySelector('input[name="search-text"]');m.addEventListener("submit",w);function w(i){if(i.preventDefault(),L(),c.value.trim()===""){n.warning({position:"topRight",message:"Please, write search word!"});return}S(),y(c.value.trim()).then(t=>{t.hits.length||n.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),b(t.hits)}).catch(t=>{console.log(t),n.error({position:"topRight",message:`Sorry, there are no images ${t} matching your search query. Please try again!`})}).finally(()=>{x(),m.reset()})}
//# sourceMappingURL=index.js.map
