import{a as g,S as y,i as n}from"./assets/vendor-CIu9XFSi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const h="52981451-85a14668d3ac889bbcbd31730";function b(i=""){return g("https://pixabay.com/api/",{params:{key:h,q:i,image_type:"photos",orientation:"horizontal",safesearch:!0}})}const c=document.querySelector(".gallery"),u=document.querySelector(".loader");function L(i){c.innerHTML=i.map(({webformatURL:s,largeImageURL:o,tags:e,likes:t,views:a,comments:d,downloads:f})=>`<li class="image-pixabay">
            <a href=${o}><img src="${s}" alt="${e}" width='360' class="image-icon"/></a>
            <ul class="image-descriptions">
              <li class="image-text">Likes <br><span>${t}</span></li>
              <li class="image-text">Views <br><span>${a}</span></li>
              <li class="image-text">Comments <br><span>${d}</span></li>
              <li class="image-text">Downloads <br><span>${f}</span></li>
            </ul>
        </li>`).join(""),new y(".image-pixabay a",{captions:!0,captionsData:"alt",captionDelay:250,overlayOpacity:1}).refresh()}function x(){c.innerHTML=""}function S(){u.classList.add("loader")}function m(){u.classList.remove("loader")}const p=document.querySelector(".form"),l=document.querySelector('input[name="search-text"]');p.addEventListener("submit",w);m();function w(i){if(i.preventDefault(),x(),l.value.trim()===""){n.warning({position:"topRight",message:"Please, write search word!"});return}S(),b(l.value.trim()).then(({data:r})=>{r.hits.length||n.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),L(r.hits)}).catch(r=>{console.log(r),n.error({position:"topRight",message:`Sorry, there are no images ${r} matching your search query. Please try again!`})}).finally(()=>{m(),p.reset()})}
//# sourceMappingURL=index.js.map
