import{a as d,S as g,i as n}from"./assets/vendor-CIu9XFSi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const y="52981451-85a14668d3ac889bbcbd31730";function h(i=""){return d("https://pixabay.com/api/",{params:{key:y,q:i,image_type:"photos",orientation:"horizontal",safesearch:!0}})}const c=document.querySelector(".gallery"),u=document.querySelector("span");function b(i){c.innerHTML=i.map(({webformatURL:o,largeImageURL:s,tags:e,likes:t,views:a,comments:p,downloads:f})=>`<li class="image-pixabay">
            <a href=${s}><img src="${o}" alt="${e}" width='360' class="image-icon"/></a>
            <ul class="image-descriptions">
              <li class="image-text">Likes <br><span>${t}</span></li>
              <li class="image-text">Views <br><span>${a}</span></li>
              <li class="image-text">Comments <br><span>${p}</span></li>
              <li class="image-text">Downloads <br><span>${f}</span></li>
            </ul>
        </li>`).join(""),new g(".image-pixabay a",{captions:!0,captionsData:"alt",captionDelay:250,overlayOpacity:1}).refresh()}function L(){c.innerHTML=""}function x(){u.classList.add("loader")}function S(){u.classList.remove("loader")}const m=document.querySelector(".form"),l=document.querySelector('input[name="search-text"]');m.addEventListener("submit",w);function w(i){if(i.preventDefault(),L(),l.value.trim()===""){n.warning({position:"topRight",message:"Please, write search word!"});return}x(),h(l.value.trim()).then(({data:r})=>{r.hits.length||n.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),b(r.hits)}).catch(r=>{console.log(r),n.error({position:"topRight",message:`Sorry, there are no images ${r} matching your search query. Please try again!`})}).finally(()=>{S(),m.reset()})}
//# sourceMappingURL=index.js.map
